# Generated by Django 3.1.4 on 2020-12-21 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('pet', models.CharField(max_length=30, verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'db_table': 'owner',
            },
        ),
        migrations.CreateModel(
            name='PetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('breed', models.CharField(max_length=30, verbose_name='Цена')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.ownermodel')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'db_table': 'pet',
            },
        ),
    ]
