# Generated by Django 3.1.4 on 2020-12-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnerModel',
            new_name='Owner',
        ),
        migrations.RenameModel(
            old_name='PetModel',
            new_name='Pet',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='pet',
            new_name='pet_name',
        ),
    ]
