# Generated by Django 3.1.4 on 2020-12-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20201221_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner_id',
            new_name='owner_name',
        ),
    ]
