# Generated by Django 3.1.4 on 2020-12-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20201221_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=30, verbose_name='Breed'),
        ),
    ]
