# Generated by Django 3.1.4 on 2020-12-29 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20201221_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets.owner'),
        ),
    ]
