# Generated by Django 3.1.4 on 2020-12-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20201229_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='pets/photos', verbose_name='Photo'),
        ),
    ]
